apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: bluegreen-demo
  labels:
    app: bluegreen-backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: bluegreen-backend
