apiVersion: v1
kind: Service
metadata:
  name: frontend-service-active
  namespace: bluegreen-demo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30080  # Your external port
  selector:
    app: nginx-bluegreen