apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend-rollout
  namespace: bluegreen-demo
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nginx-bluegreen
  template:
    metadata:
      labels:
        app: nginx-bluegreen
    spec:
      containers:
      - name: nginx
        image: saimanasg/bluegreen-frontend:12
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
  strategy:
    blueGreen:
      activeService: frontend-service-active
      previewService: frontend-service-preview
      autoPromotionEnabled: false  
      scaleDownDelaySeconds: 30