apiVersion: v1
kind: Service
metadata:
  name: frontend-service-preview
  namespace: bluegreen-demo
  labels:
    app: nginx-bluegreen
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30081
  selector:
    app: nginx-bluegreen